### PR TITLE
fixed broken link to oneccl spec

### PR DESCRIPTION
**Pull request by bdmoore1**
I fixed the link to the oneccl specification on the https://oneapi-src.github.io/oneCCL/programming-model.html page. This gh-pages PR is to update the public pages.

The sharepoint preview is not working right now, so if you want to see an output, download the zip below, extract all, and open the index page. Or just open the programming-model page, it's the one with the broken link.

https://intel-my.sharepoint.com/:u:/p/benjamin_d_moore/EfUzg6ZeiA5IvGE4ZSX2Xx8BG9lYXf8E19Oy3gTfF99yuA?e=NR5kFz

### CODE REVIEW

**Review by i-kosarev — APPROVED** [review]
LGTM

**Comment by maciekpac** [comment]
I can see there are a lot of changes here. Is that because you made a general update of gh-pages ?

**Comment by bdmoore1** [comment]
> I can see there are a lot of changes here. Is that because you made a general update of gh-pages ?

Yes, whenever we build a new set of html files to capture changes in one file, github recognizes all files as having changed, even if there are no changes to the rest of the files.

**Comment by maciekpac** [comment]
image

a lot of files were deleted, were that temporary files that had accidentally been published before ? There is no notion about that in the PR description

**Comment by bdmoore1** [comment]
> image
> 
> a lot of files were deleted, were that temporary files that had accidentally been published before ? There is no notion about that in the PR description

Yes, they are unnecessary files that were published in the past. Our tools team made a change to the script to stop producing those files. I forgot to mention that in the PR.

**Review by maciekpac — APPROVED** [review]

**Review by nikitaxgusev — APPROVED** [review]

**Pull request merged**
